name-template: 'PSLab Version $NEXT_PATCH_VERSION'
tag-template: v$NEXT_PATCH_VERSION
change-template: '- $TITLE (#$NUMBER) - @$AUTHOR'
categories:
  - title: ':rocket: Features and Enhancements'
    labels:
      - 'Feature'
      - 'Enhancement'
  - title: ':bug: Bug Fixes'
    label: 'Bug'
  - title: ':wrench: Maintenance'
    labels:
      - 'Chore'
      - 'Documentation'
template: |-
    ## Changes
    $CHANGES

    This release was made possible thanks to $CONTRIBUTORS
