name: pslab
description: "PSLab app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: '3.47.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.3

  cupertino_icons: ^1.0.9
  flutter_svg: ^2.3.0
  google_fonts: ^8.2.1
  fl_chart: ^1.2.0
  provider: ^6.1.5
  get_it: ^9.2.1
  record: ^7.1.1
  data: ^0.15.1
  logger: ^2.8.0
  url_launcher: ^6.3.2
  font_awesome_flutter: ^11.0.0
  package_info_plus: ^10.2.1
  sensors_plus: ^7.1.0
  sleek_circular_slider: ^2.1.0
  gauge_indicator: ^0.6.0
  light: ^5.0.0
  connectivity_plus: ^7.3.1
  carousel_slider: ^5.1.1
  vibration: ^3.2.1
  shared_preferences: ^2.5.5
  csv: ^8.0.0
  share_plus: ^13.3.0
  path_provider: ^2.1.6
  file_picker: ^12.2.0
  flutter_screenutil: ^5.9.3
  inno_bundle: ^0.12.0
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  geolocator: ^14.0.3
  wakelock_plus: ^1.8.0
  image: ^4.9.2
  web: ^1.1.1
  mp_audio_stream: ^0.2.2
  ffi: ^2.2.0
  home_widget: ^0.9.4
  girix_code_gauge: ^0.0.6
  image_picker: ^1.2.3
  rust_lib_pslab:
    path: rust_builder
  flutter_rust_bridge: 2.13.0
  pdf: ^3.11.0
  printing: ^5.12.0
  web_socket_channel: ^3.0.3
  freezed_annotation: ^3.1.0
  archive: ^4.0.9
  http: ^1.6.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_oss_licenses: ^3.2.0
  build_runner: ^2.16.1
  freezed: ^4.0.1

flutter:
  generate: true

  fonts:
    - family: Digital-7
      fonts:
        - asset: fonts/Digital-7.ttf
        - asset: fonts/Digital-7-Italic.ttf
          style: italic

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/guide_images/

inno_bundle:
  id: b633ddbf-a022-4cbb-a459-4ba9fec0da51
  name: PSLab
  publisher: FOSSASIA
  url: https://pslab.io
  support_url: https://github.com/fossasia/pslab-app/issues
  updates_url: https://github.com/fossasia/pslab-app/releases

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"
  adaptive_icon_monochrome: "assets/icons/icon.png"
  adaptive_icon_foreground_inset: 22

  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#0175C2"

  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/icons/icon.png"
