name: Push

on:
  push:
    branches:
      - master
      - development
      - versions

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch-name.outputs.current_branch }}

    steps:
      - name: Download repository
        uses: actions/checkout@v3
        with:
          ref: versions

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Update version
        id: update_version
        run: |
          version_name_file=versionName
          version_name=$(sed -n '1p' $version_name_file)
          IFS='.' read -r -a version_parts <<< "$version_name"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          next_patch=$((patch + 1))
          next_patch_version_name="$major.$minor.$next_patch"
          
          echo "VERSION_NAME=$next_patch_version_name" >> $GITHUB_ENV
          
          version_code_file=versionCode
          version_code=$(sed -n '1p' $version_code_file)
          new_version_code=$((version_code + 1))
          echo "VERSION_CODE=$new_version_code" >> $GITHUB_ENV
          
          echo "${{ env.VERSION_NAME }}" > $version_name_file
          echo "${{ env.VERSION_CODE }}" > $version_code_file
          
          git config --global user.name "${{ github.workflow }}"
          git config --global user.email "gh-actions@${{ github.repository_owner }}"
          
          git add .
          git commit -m"Update versionName to ${{ env.VERSION_NAME }} and versionCode to ${{ env.VERSION_CODE }}"
          
          git push origin versions          

      - name: Checkout development branch
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Prepare Build Keys
        env:
          ENCRYPTED_F10B5E0E5262_IV: ${{ secrets.ENCRYPTED_F10B5E0E5262_IV }}
          ENCRYPTED_F10B5E0E5262_KEY: ${{ secrets.ENCRYPTED_F10B5E0E5262_KEY }}
        run: |
          bash scripts/prep-key.sh

      - name: Build with Gradle
        env:
          STORE_PASS: ${{ secrets.STORE_PASS }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PASS: ${{ secrets.KEY_PASS }}
          VERSION_CODE: ${{ env.VERSION_CODE }}
          VERSION_NAME: ${{ env.VERSION_NAME }}
        run: |
          bash ./gradlew build --stacktrace
          bash ./gradlew bundle --stacktrace

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: APK Debug generated
          path: app/build/outputs/apk/debug

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: APK Release generated
          path: app/build/outputs/apk/release

      - name: Upload AAB Release
        uses: actions/upload-artifact@v4
        with:
          name: AAB Release generated
          path: app/build/outputs/bundle/release

      - name: Upload APK/AAB's to apk branch
        run: |
          git config --global user.name "${{ github.workflow }}"
          git config --global user.email "gh-actions@${{ github.repository_owner }}"
          
          git clone --branch=apk https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }} apk
          cd apk
          
          if [[ ${{ github.ref_name }} =~ ^(master)$ ]]; then
            rm -rf *
          else
            rm -rf pslab-dev*
          fi
          ls
          
          find ../app/build/outputs -type f \( -name '*.apk' -o -name '*.aab' \) -exec cp -v {} . \;
          
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          
          for file in app*; do
            mv $file pslab-$branch-${file#*-}
          done
          
          git checkout --orphan temporary
          git add --all .
          git commit -am "[Auto] Update APK/AAB's from $branch ($(date +%Y-%m-%d.%H:%M:%S))"
          git branch -D apk
          git branch -m apk
          git push --force origin apk